# Generated by Django 6.0.3 on 2026-03-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
    ]
